### ISSUE TITLE
gotop on OpenWRT

### ISSUE THREAD

**Issue by lucenera** [cjbassi/gotop#113]
Hi,
I tried to use gotop on OpenWRT. It starts, but I can not see the processes running. The affected log file shows that you can run the 'ps' command.

Required information:

- gotop version: 2.0.2
- output of uname -a: Linux OpenWrt 4.14.95 #0 SMP Mon Jan 28 08:54:32 2019 armv7l GNU/Linux
- Terminal emulator: gnome terminal v. 3.28.2
- ssh version: OpenSSH_7.6p1 Ubuntu-4ubuntu0.2, OpenSSL 1.0.2n  7 Dec 2017
[errors.log](https://github.com/cjbassi/gotop/files/2877721/errors.log)

- Linux: `~/.local/state/gotop/errors.log`

**Comment by cjbassi** [comment]
I'm thinking this is because OpenWRT uses busybox, and the `ps` command provided by busybox works differently than on standard Linux or macOS. There's actually an open issue for busybox support here: #110 Aside from adding busybox support, I guess the only other option is you could replace the `ps` command used. So I think I'm going to close this issue, but let me know if you figure out anything else.
