### ISSUE TITLE
Didn't show usage of cpu and memory of chrome on macos

### ISSUE THREAD

**Issue by Friday21** [cjbassi/gotop#146]
mac: 10.14.0
gotop: 1.4.1

while using gotop, I can't find the usage of  chrome, while use htop, I can find it.
(left:htop, right: gotop, and also, the cpu usage of pycharm did not match with htop and gotop...)

![Screen Shot 2019-05-31 at 11 27 47 AM](https://user-images.githubusercontent.com/10892548/58679806-9aaf7080-8397-11e9-8c2d-3c671045520d.png)

**Comment by cjbassi** [comment]
The Chrome issue should be fixed in the latest version.

For PyCharm, the discrepancy is due to the fact that htop reports CPU usage relative to a single core, while gotop reports overall CPU usage. #104 is still open and that would add a flag that would allow for toggling between the 2 behaviors if you're interested in that.
