### ISSUE TITLE
Crash on FreeBSD: concurrent map read and map write

### ISSUE THREAD

**Issue by An-Sar** [cjbassi/gotop#94]
This crash takes a while to manifest, gotop runs and all appears to be working normally, but if left running eventually it quietly crashes back to the command prompt. What's interesting is clicking on the terminal generates a series of garbage characters as if the tty has been overloaded. The error log is attached.

gotop 1.7.1, installed from freebsd ports

FreeBSD test 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+fc3d65faae6(HEAD) amd64
FreeBSD test 12.0-RELEASE FreeBSD 12.0-RELEASE r341666 GENERIC  i386

the freebsd 11.2 system is a jail running on FreeNAS, while the 12.0 system is a laptop
shell is zsh and the terminal emulator is urxvt (xorg/freebsd) and iTerm2 (osx)

[gotop_fbsd_11_2_amd64_crash.txt](https://github.com/cjbassi/gotop/files/2774536/gotop_fbsd_11_2_amd64_crash.txt)

**Comment by cjbassi** [comment]
How long does it usually take for this to happen?

Yah so this is most likely because of a data race since there's 2 independent 1 second timers, 1 timer for drawing the widgets (reading), and 1 for updating the widgets (writing). I had thought there wouldn't be a conflict if the timers stayed in sync but I guess not. I'll just have to add some mutexes. I'm curious if this is a FreeBSD issue, if maybe the timers are implemented differently, but either way I should add the mutexes.

**Comment by An-Sar** [comment]
it seems to be an arbitrary amount of time, i originally noticed it quite quickly but since you're reply i tried to measure with a timestamp on the shell prompt and it hasn't died yet.. sorry that is not very helpful.

**Comment by cjbassi** [comment]
So the issue should be fixed in `master` with 97f490be800eb3dd2092c7a1cce339272456e024, so I'm gonna go ahead and close this, but let me know if you get the crash again after updating.

**Comment by cjbassi** [comment]
Actually should be fixed now with cf0092074563a70706d8b9914de4ccbdcc16eb2f, just had to fix one thing.

**Comment by An-Sar** [comment]
awesome, i've build this version from git and will update if i run into anything. Thank You.
